### ISSUE TITLE
東京都が遠くに表示される

### ISSUE THREAD

**Issue by takamotobiz** [geolonia/tile-builder#19]
国名や都市名をバウンディングボックスの中心に表示しているためいい感じの位置に文字が表示されない場合がある。ロシアやフランス、アメリカも同様である。
![image](https://user-images.githubusercontent.com/74547674/102024977-5c8e6c00-3dd8-11eb-9fea-e8c14878b9af.png)

**Comment by kamataryo** [comment]
FYI. 以下はポリゴンの内部にあることが保証されていて、ラベルの位置決定などに適している代表点を求めるライブラリです。
https://github.com/mapbox/polylabel

**Comment by takamotobiz** [comment]
ShaplyにてSplitして最大面積の部分要素に対してpolylabelを行うとよさそう。

**Comment by takamotobiz** [comment]
ご指摘ありがとうございます。
Shaplyに実装されているpolylabelを使いました。また、MultiPolygonの場合は最大面積のポリゴンを対象としています。
これで基本的には問題ないのですが、NaturalEarthのポリゴンデータが"Invalid Polygon"となるケースがいくつかありました。
この対処として、polylabelの例外発生時にはMBRの中心座標にラベルを表示するようにしました。
