### ISSUE TITLE
フランス周辺で文字化け

### ISSUE THREAD

**Issue by takamotobiz** [geolonia/tile-builder#20]
フランスの県名で文字化けが顕著。
![image](https://user-images.githubusercontent.com/74547674/102025213-db37d900-3dd9-11eb-8e7e-1fffbd6c9532.png)

**Comment by kamataryo** [comment]
こちらは、文字化けではなく文字の区切りではないでしょうか？
[ロワール＝エ＝シェール県](https://ja.wikipedia.org/wiki/%E3%83%AD%E3%83%AF%E3%83%BC%E3%83%AB%EF%BC%9D%E3%82%A8%EF%BC%9D%E3%82%B7%E3%82%A7%E3%83%BC%E3%83%AB%E7%9C%8C)

この文字区切りのことはダブルハイフンと呼ぶそうです。
https://ja.wikipedia.org/wiki/%E3%83%80%E3%83%96%E3%83%AB%E3%83%8F%E3%82%A4%E3%83%95%E3%83%B3

**Comment by takamotobiz** [comment]
ありがとうございます。
QGISで元データを確認したところ、ご指摘の通りでした。
![image](https://user-images.githubusercontent.com/74547674/102138397-9eceb080-3e9f-11eb-8c58-1c7130d90347.png)
