### ISSUE TITLE
ID の変更

### ISSUE THREAD

**Issue by miya0001** [geolonia/tile-builder#25]
現状 `openmaptiles` になってしまっているので変更しましょう。
https://github.com/geolonia/tile-builder/blob/master/update.sql#L1

* `geolonia` というプレフィックスをつける？
* 添付するスタイルも弊社製のスタイルにしたほうがいい気がします。
  * フォントやアイコンの出典元を明確にするためにもそのほうがいい気がする。
  * 本リポジトリ内で対処しているフォントに関連する諸々が不要になる？

**Comment by miya0001** [comment]
Note: SQLite用のSQLファイル

**Comment by miya0001** [comment]
`oceanus` を ID とする。

**Comment by takamotobiz** [comment]
IDをoceanusに変更しました。
