### ISSUE TITLE
`./tile-builder.sh` 等のコマンドについて

### ISSUE THREAD

**Issue by miya0001** [geolonia/tile-builder#31]
* [ ] デフォルト値がほしい。`build` 等。
* [ ] 相対パスを可能に。
* [ ] ポートの引数は `-p` みたいな渡し方がいいかも。
* [ ] 動詞、名詞が統一されてない。

**Comment by takamotobiz** [comment]
オプション指定、デフォルト設定などに対応しました。
相対パスにも対応しましたが、”~”（チルダ）には未対応です。。
スクリプト名も修正していますが、気になる点は遠慮なくご指摘ください。

**Comment by takamotobiz** [comment]
本件も大丈夫そうかな。。と思っています。
一旦クローズします。
