### ISSUE TITLE
README に記載されている URL を gh-pages または geolonia 関連のドメインに変更する

### ISSUE THREAD

**Issue by miya0001** [geolonia/tile-builder#33]
https://github.com/geolonia/tile-builder/blob/master/README.md#%E5%A4%89%E6%8F%9B%E7%B5%90%E6%9E%9C%E8%A1%A8%E7%A4%BAurl

ステージング環境を構築する必要がある。 #27

**Comment by takamotobiz** [comment]
以下を作成しましたので、お手数ですがgh-pagesの作成をお願いします。
`docs/oceanus.html`

**Comment by takamotobiz** [comment]
gh-pagesを設定しREADME含め下記URLに変更しました。
https://geolonia.github.io/oceanus/oceanus.html
