### ISSUE TITLE
NaturalEarthデータの静的サイト

### ISSUE THREAD

**Issue by takamotobiz** [geolonia/tile-builder#35]
NaturalEarthデータは、複数のシェープファイルを1つのzipファイルとして提供されていますので、tile-builder実行のために231MBのファイルをダウンロードする必要があります。
個別のシェープファイルを公開する静的サイト（github.ioでも可）を立てれば、yamlに記載されているシェープファイル だけをダウンロードすることができます。
NaturalEarthデータはパブリックドメインとのことなので、再頒布も大丈夫だとは思っています。
また、シェープファイルの一覧や内容を示すメタ情報をどうするかは課題になると思いますが。。

**Comment by miya0001** [comment]
あっ、これはうちのほうで手間が増えるので不要かなと思います。

**Comment by takamotobiz** [comment]
ありがとうございます。
了解しました。クローズします。
