### ISSUE TITLE
ソース内の日本語のコメントの削除

### ISSUE THREAD

**Issue by miya0001** [geolonia/tile-builder#36]
海外のユーザーもターゲットになるため、少なくともソースコード内の日本語のコメントは削除、または英語で記述するようにしましょう。
あと、恐縮なのですが、個人名でのライセンスの記述も削除をお願いします。

https://github.com/geolonia/oceanus/blob/master/GJWriter.py

**Comment by takamotobiz** [comment]
以下の2つのコミットにて対応しました。お時間ある時にご確認を。
6127fe7448b3a456ff2c88dc8371ce78500a6b83　（ソース、関連スクリプトの修正）
ac7bb3efa0c47a2f1a518b3d83bc46ec3f7defa2　　（READMEの修正）

**Comment by takamotobiz** [comment]
本件、ご確認いただけたようですのでクローズします。
問題あればご指摘ください。
