### ISSUE TITLE
カスピ海の南側の国境がおかしい？

### ISSUE THREAD

**Issue by miya0001** [geolonia/tile-builder#46]
![カスピ海南](https://user-images.githubusercontent.com/309946/107940336-6ea0ac80-6fcb-11eb-93e2-929ccec21915.png)

**Comment by takamotobiz** [comment]
ご指摘ありがとうございます。
国境線と州の境界線がずれているというご指摘かと思います。
Oceanusの元データであるNaturalEarthデータは、精度の異なる3種類の地図（分解能が110m、50m、10m）が提供されており、３種類の地図間には許容誤差範囲での座標のズレがあります。
ご指摘の問題は、国境と州境の各レイヤを異なる縮尺のNaturalEarthデータを使用したために発生しています。
具体的には添付のように（レイヤごとの元シェープファイルの定義ファイル）、同じplaceレイヤにてズームレベル0−6が110mの国境を表示し、ズームレベル5−7では10mの州境を表示しているため表示が重複するズームレベル5、6では、ご指摘のような表示となってしまいます。
この対策として、国境線についても10mを採用することとし、他のデータについても同様の見直しを行います。
![image](https://user-images.githubusercontent.com/74547674/107953902-196e9600-6fdf-11eb-8f1b-0f61702c687d.png)

**Comment by takamotobiz** [comment]
50m国境線レイヤを10mに変更することで、この現象はなくなっています。
以下で確認できます。
https://labo.takamoto.biz/oceanus2/
