### ISSUE TITLE
北方領土

### ISSUE THREAD

**Issue by miya0001** [geolonia/tile-builder#47]
![Oceanus___Natural_Earthベクトルタイル](https://user-images.githubusercontent.com/309946/107940399-811ae600-6fcb-11eb-9781-69702103781a.png)

**Comment by takamotobiz** [comment]
国土地理院の地図上では添付になっていますので、Oceanus地図をそちらに合わせる方向で検討します。
![image](https://user-images.githubusercontent.com/74547674/107949409-921e2400-6fd8-11eb-94f4-fbde191e8b46.png)

**Comment by takamotobiz** [comment]
一時的な対処として、問題の国境線が収容されている50mの国境線シェープファイルを10mに変更しました。
調査が必要ですが、mbtilesのデータサイズは若干小さくなっています。

**Comment by takamotobiz** [comment]
地理院の数値地図500万から海上の国境線を追加しコミットしました。
f3b2c3d2a032bec70ab0d1a57a2f6c0936ad1a9f
以下にてご確認いただけます。
https://geolonia.github.io/oceanus/oceanus.html
現時点では、以下の問題・課題があります。
1. 数値地図500万利用に関する国土地理院への届出：私の方で届出の作業を行います。
2. 千島列島東端の日本の国境とロシアの州境の重複：スタイルでフィルタできないか元データのNEをもう少し調査します。

なお、国境線追加処理は以下のように行っています。
- 数値地図500万の境界データを収容した"5M_BL.xml"から種別”国界(海上)”を取得してGeoJSON（jpgis2geojson.json）に変換
- jpgis2geojson.jsonをtippecanoeを使ってmbtiles（japanborder.mbtiles）に変換
- tile-joinを使ってoceanus.mbtilesとjapanborder.mbtilesを結合してoceanus2.mbtilesを作成  

変換を行うPythonスクリプト（jpgis2geojson.py）および正しい国境線を収容したmbtiles（japanborder.mbtiles）は、ディレクトリjapan-blに収容していますが、元データである数値地図500万の"5M_BL.xml"は、公開・再頒布を含め国土地理院への確認中ですのでGitHub上には配置していません。

**Comment by takamotobiz** [comment]
以下のコミットで、問題の州境線（note=Russsa1000）を削除しました。
eb0aac5cc7673ef10206523ec6c03dd15296170d

**Comment by takamotobiz** [comment]
一連の対応により、本問題は解決したと考えています。
