### ISSUE TITLE
oc-lakeが日本の一部の湖で表示されている

### ISSUE THREAD

**Issue by naogify** [geolonia/tile-builder#63]
Related to https://github.com/geolonia/basic/pull/12

`oc-lake-ja`が日本、`oc-lake`レイヤーは海外の湖のレイヤーだと思うのですが、`oc-lake` レイヤーで琵琶湖などで表示されてしまっています。

https://deploy-preview-12--style-basic.netlify.app/#17.74/35.200305/136.054579

![スクリーンショット 2021-06-11 14 57 17](https://user-images.githubusercontent.com/8760841/121638342-c3f65180-cac5-11eb-850e-4b5d591ecac5.png)

**Comment by takamotobiz** [comment]
@naogify @keichan34 ご指摘ありがとうございました。
タイル側の問題（oceanusのlake要素にjaフラグが未設定）でしたので、tsglのoceanusタイルを正しいものに入れ替えました。
https://tsgl.internal.geolonia.com/oceanus2/styles/2tile-splitwater/#8.06/35.255/136.439
ただ、tsglですとzoomlevel=8以上のlakeが表示されずに湖が干上がったような感じになるんですよね。。

**Comment by naogify** [comment]
@takamotobiz ありがとうございました! z8以上で干上がる問題は、`geolonia-water`(https://tileserver.geolonia.com/water/tiles.json) が日本国内の川、湖のポリゴンを持っていなかったので、  "id": "water-river-lake-ja" を追加することで解決しました。
